
import { join } from 'node:path'
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'


export default defineEventHandler(async (event) => {
    try {
        const body = await readBody(event)
        const { id, outputFolder } = body

        const db = useDB()
        const row = db.prepare('SELECT * FROM generations WHERE id = ?').get(id) as any

        if (!row) {
            throw createError({ statusCode: 404, statusMessage: 'Generation not found' })
        }

        // --- STEP 1: GEMINI ---
        console.log(`[Process] Processing ID ${id} with Status ${row.status}`)
        if (row.status === 'PENDING_GEMINI') {
            console.log('[Process] Starting Gemini Generation...')
            // 1. Call Gemini to get 2 songs
            const songs = await kie.generateSongList(row.mood, 2)
            console.log('[Process] Gemini Response:', songs)

            // Update DB
            db.prepare(`
      UPDATE generations 
      SET song_name_1 = ?, lyric_prompt = ?, 
          song_name_2 = ?, 
          status = 'PENDING_MUSIC'
      WHERE id = ?
    `).run(
                songs.title1,
                JSON.stringify({ p1: songs.lyric_prompt }),
                songs.title2,
                id
            )

            return { status: 'PENDING_MUSIC', msg: 'Gemini generation complete' }
        }

        // --- STEP 2: SKIPPED (Lyrics generated by Suno) ---

        // --- STEP 3: MUSIC ---
        if (row.status === 'PENDING_MUSIC') {
            if (!row.suno_task_id) {
                const getRandom = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min

                const wVal = getRandom(row.weirdness_min || 40, row.weirdness_max || 60)
                const sVal = getRandom(row.style_influence_min || 40, row.style_influence_max || 60)
                const bpmVal = getRandom(row.bpm_min || 100, row.bpm_max || 130)

                // Parse the prompt from Gemini
                const prompts = JSON.parse(row.lyric_prompt || '{}')
                const descriptionPrompt = prompts.p1 || row.mood

                // Construct a full prompt for Description Mode
                // Combining Style + Description for better control in V3/V3.5/V4 (V5 typically handles this well too)
                // Using the user-provided style prompt as 'tags' still, but appending to description if needed
                // Based on "Description Mode", we usually put everything in the prompt.
                // However, our kie wrapper puts 'tags' into 'style' field.
                // If customMode=false, Suno API (via Kie) might use 'gpt_description_prompt'.
                // Let's rely on the updated Kie wrapper which maps 'prompt' to 'prompt' and 'tags' to 'style'.

                const taskPayload = {
                    prompt: descriptionPrompt,
                    tags: row.style_prompt,
                    title: row.song_name_1,
                    weirdness: wVal,
                    bpm: bpmVal,
                    styleInfluence: sVal,
                    customMode: false // Use Description Mode
                }

                const task = await kie.generateMusic(taskPayload)
                console.log('[Process] Suno Task Response:', task)

                if (task && task.taskId) {
                    db.prepare("UPDATE generations SET suno_task_id = ? WHERE id = ?").run(task.taskId, id)
                    return { status: 'PENDING_MUSIC', msg: 'Music generation started' }
                } else {
                    console.error('[Process] Suno Task Missing ID:', task)
                    return { status: 'PENDING_MUSIC', msg: 'Failed to start music (Kie returned no Task ID)' }
                }

            } else {
                // Check Status
                const info = await kie.getTaskInfo(row.suno_task_id)
                // Debug logging to see exactly what we get
                console.log(`[Process] Poll details for ${row.suno_task_id}:`, {
                    status: info?.status,
                    hasResponse: !!info?.response,
                    hasSunoData: !!info?.response?.sunoData,
                    keys: info ? Object.keys(info) : 'null'
                })

                if (info && (info.status === 'SUCCESS' || info.progress === 100)) {
                    // Handle various potential response structures
                    const clips = info.response?.sunoData || info.sunoData || info.clips || []
                    console.log(`[Process] Clips found: ${clips.length}`)

                    if (clips && clips.length >= 2) {
                        // Extract lyrics from metadata if available
                        const l1 = clips[0].metadata?.prompt || clips[0].prompt || 'No lyrics found in metadata'
                        const l2 = clips[1].metadata?.prompt || clips[1].prompt || 'No lyrics found in metadata'

                        db.prepare(`
               UPDATE generations 
               SET audio_url_1 = ?, audio_url_2 = ?, 
                   lyrics_content = ?,
                   status = 'DOWNLOADING' 
               WHERE id = ?
             `).run(clips[0].audioUrl, clips[1].audioUrl, JSON.stringify({ l1, l2 }), id)
                        return { status: 'DOWNLOADING', msg: 'Music ready' }
                    }
                }
                return { status: 'PENDING_MUSIC', msg: 'Waiting for music...' }
            }
        }

        // --- STEP 4: DOWNLOAD ---
        if (row.status === 'DOWNLOADING') {
            if (!outputFolder) throw createError({ statusCode: 400, statusMessage: 'Output folder required' })

            // Helper to download
            const downloadFile = async (url: string, prefix: string, songName: string) => {
                const blob = await $fetch(url, { responseType: 'blob' }) as Blob
                const buffer = Buffer.from(await blob.arrayBuffer())

                let batchIdx = 1
                while (true) {
                    const batchDir = join(outputFolder, `Batch_${String(batchIdx).padStart(2, '0')}`)
                    if (!existsSync(batchDir)) mkdirSync(batchDir, { recursive: true })

                    const files = readdirSync(batchDir)
                    if (files.length < 10) {
                        const safeName = songName.replace(/[^a-z0-9]/gi, '_').toLowerCase()
                        const path = join(batchDir, `${prefix}_${safeName}.mp3`)
                        writeFileSync(path, buffer)
                        return path
                    }
                    batchIdx++
                }
            }

            const path1 = await downloadFile(row.audio_url_1, '1', row.song_name_1)
            const path2 = await downloadFile(row.audio_url_2, '2', row.song_name_2 || row.song_name_1 + '_v2')

            db.prepare(`
      UPDATE generations 
      SET local_path_1 = ?, local_path_2 = ?, status = 'COMPLETED' 
      WHERE id = ?
    `).run(path1, path2, id)

            return { status: 'COMPLETED', msg: 'Files downloaded' }
        }

        return { status: row.status, msg: 'No action taken' }
    } catch (e: any) {
        console.error('[Process Error]', e)
        throw createError({ statusCode: 500, statusMessage: e.message || 'Internal Server Error' })
    }
})
